import { describe,it,expect } from 'vitest';
import { mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,chmodSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { FrontendReleases,frontendFiles } from '../server/frontend-releases.js';
import { sourceFingerprint } from '../server/version.js';
function fixture(){const root=mkdtempSync(join(tmpdir(),'frontend-release-')),snapshot=join(root,'snapshot'),runtime=join(root,'runtime');for(const dir of [snapshot,runtime]){for(const p of ['src','scripts','server/public'])mkdirSync(join(dir,p),{recursive:true});for(const file of ['package.json','package-lock.json','server/public/sw.js'])writeFileSync(join(dir,file),'same');}for(const name of frontendFiles)writeFileSync(join(snapshot,'server/public',name),name==='panel.html'?'<head></head><script src="/workspace.js"></script>':name);const releases=new FrontendReleases(join(root,'state'),sourceFingerprint(snapshot));return{root,snapshot,runtime,releases};}
describe('independent frontend releases',()=>{
 it('publishes atomically, versions assets, retains old tabs and supports rollback',()=>{const f=fixture(),a=f.releases.publish(f.snapshot,'a'.repeat(40),f.runtime);expect(f.releases.current()?.id).toBe(a.id);expect(f.releases.html(a,{})).toContain('/ui-releases/'+a.id+'/workspace.js');writeFileSync(join(f.snapshot,'server/public/workspace.js'),'new JS');const b=f.releases.publish(f.snapshot,'b'.repeat(40),f.runtime);expect(f.releases.asset(a.id,'workspace.js').toString()).toBe('workspace.js');expect(f.releases.asset(b.id,'workspace.js').toString()).toBe('new JS');f.releases.rollback();expect(f.releases.current()?.id).toBe(a.id);});
 it('can roll the first publication back to image assets',()=>{const f=fixture();f.releases.publish(f.snapshot,'a'.repeat(40),f.runtime);f.releases.rollback();expect(f.releases.current()).toBeUndefined();});
 it.each(['src/changed.ts','package-lock.json','server/public/sw.js'])('rejects incompatible %s changes without replacing the active frontend',file=>{const f=fixture(),a=f.releases.publish(f.snapshot,'a'.repeat(40),f.runtime);writeFileSync(join(f.snapshot,file),'changed');expect(()=>f.releases.publish(f.snapshot,'b'.repeat(40),f.runtime)).toThrow(/changed|backend/);expect(f.releases.current()?.id).toBe(a.id);});
 it('rejects incomplete bundles, corrupted assets and traversal',()=>{const f=fixture(),a=f.releases.publish(f.snapshot,'a'.repeat(40),f.runtime);rmSync(join(f.snapshot,'server/public/workspace.css'));expect(()=>f.releases.publish(f.snapshot,'b'.repeat(40),f.runtime)).toThrow();expect(f.releases.current()?.id).toBe(a.id);expect(()=>f.releases.asset(a.id,'../current.json')).toThrow();expect(()=>f.releases.asset('../','panel.html')).toThrow();chmodSync(join(f.releases.root,a.id,'workspace.js'),0o644);writeFileSync(join(f.releases.root,a.id,'workspace.js'),'corrupt');expect(()=>f.releases.activate(a.id)).toThrow('checksum');});
 it('ignores a frontend from an incompatible backend after a backend upgrade',()=>{const f=fixture();f.releases.publish(f.snapshot,'a'.repeat(40),f.runtime);expect(new FrontendReleases(join(f.root,'state'),'different').current()).toBeUndefined();});
});
