const $=id=>document.getElementById(id),app=document.querySelector('.app');
const initialMessages=$('messages').innerHTML;let active='proposal',account='B',automatic=true,version=3,ref=false,attachmentNames=[],dialogReturn=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,3500)}
function modal(title,html){dialogReturn=document.activeElement;$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;if(!$('dialog').open)$('dialog').showModal()}
function closeModal(){$('dialog').close();dialogReturn?.focus()}
$('closeDialog').onclick=closeModal;
$('dialog').addEventListener('click',e=>{if(e.target===$('dialog')){const r=$('dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
function showFiles(tab='preview'){if(active!=='proposal'){modal('Conversation files','<p>No saved files yet. Attach a file to start working on it.</p><p class="dialog-note">File selection in this draft stays local.</p>');return}app.classList.remove('files-closed');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==tab)}
$('closeInspector').onclick=()=>app.classList.add('files-closed');$('filesToggle').onclick=()=>app.classList.contains('files-closed')?showFiles():app.classList.add('files-closed');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showFiles(b.dataset.tab));
function setVersion(n){version=n;$('previewVersion').textContent=`Version ${n} · ${n===3?'Current':'Original'}`;$('download').href=`https://x056.think.val.id/rc-chat-AHU-proposal-v${n}.docx`;document.querySelector('.paper .doc-intro').textContent=n===3?'Scope of work & delivery plan':'Initial scope of work';showFiles();}
function versions(){modal('Document versions',`<p>Each revision keeps a downloadable copy.</p>${[3,2].map(n=>`<button class="choice ${n===version?'selected':''}" data-v="${n}"><span class="file-icon">W</span><span><b>Version ${n}${n===3?' · Current':''}</b><small>${n===3?'Revised scope and delivery schedule · Account B':'Original document · Uploaded by you'}</small></span><span class="badge">Preview ↗</span></button>`).join('')}<p class="dialog-note">These downloads contain sample proposal content.</p>`);document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{setVersion(Number(b.dataset.v));closeModal()})}
$('versions').onclick=versions;$('versionPicker').onclick=versions;document.querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>setVersion(Number(b.dataset.version)));
function accounts(){modal('Account for this chat',`<p>${esc($('provider').value)} · Demo account availability</p><button class="choice ${automatic?'selected':''}" id="autoAccount"><span>⇄</span><span><b>Automatic</b><small>Continue on another available account when needed.</small></span><span class="badge">${automatic?'Selected':''}</span></button><button class="choice" disabled><span class="avatar">A</span><span><b>Account A</b><small>Usage limit reached · Resets in 2h 14m</small><div class="quota"><i style="width:100%;background:#b69676"></i></div></span><span class="badge">Limited</span></button>${['B','C'].map(a=>`<button class="choice ${!automatic&&account===a?'selected':''}" data-account="${a}"><span class="avatar">${a}</span><span><b>Account ${a}</b><small>${a==='B'?'62':'89'}% remaining in this demo</small><div class="quota"><i style="width:${a==='B'?62:89}%"></i></div></span><span class="badge">${account===a?'In use':'Available'}</span></button>`).join('')}<p class="dialog-note">Automatic switching stays within the selected provider. A pinned account waits for capacity.</p>`);$('autoAccount').onclick=()=>{automatic=true;updateAccount();closeModal();toast('Automatic account switching enabled')};document.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>{account=b.dataset.account;automatic=false;updateAccount();closeModal();toast(`Pinned to Account ${account}`)})}
function updateAccount(){$('accountControl').innerHTML=`<span>Account</span><b><i class="dot"></i> ${automatic?'Auto · ':''}${account} ⌄</b>`;$('routingNote').textContent=automatic?'Switch accounts when needed · Same provider':`Pinned to Account ${account} · Wait if limited`}
['accountControl','poolSettings','routingSettings'].forEach(id=>$(id).onclick=accounts);
function details(){modal('Account switch',`<p>Account A reached its usage limit during document editing.</p><div class="choice"><span>⇄</span><span><b>Resumed with Account B</b><small>Same provider · Same conversation</small></span><span class="badge">Completed</span></div><p>The conversation and saved files were retained. Any interrupted operation may need to run again.</p><p class="dialog-note">This draft simulates the switch. It does not use your accounts.</p><div class="dialog-footer"><button class="small-button" id="manageSwitch">Manage accounts</button></div>`);$('manageSwitch').onclick=accounts}
$('limitDemo').onclick=()=>{if(active!=='proposal')loadChat('proposal');automatic=true;account='B';updateAccount();$('handoff').style.background='#f1f6eb';$('handoff').scrollIntoView({behavior:'smooth',block:'center'});details()};
function references(){modal('Reference a conversation',`<p>Read project context or ask its conversation for an update.</p><button class="choice" id="pickReference"><span>▱</span><span><b>AHU · Proposal scope</b><small>Scope decisions, exclusions, and delivery dates</small></span><span class="badge">${ref?'Added':'Add +'}</span></button><button class="choice" id="pickDeployment"><span>▱</span><span><b>Remote Control · Deployment</b><small>Latest release and deployment status</small></span><span class="badge">View ↗</span></button><p class="dialog-note">References are selected explicitly. Remove them from the composer at any time.</p>`);$('pickReference').onclick=()=>{ref=true;renderRefs();closeModal();showFiles('context');toast('Proposal scope added as a reference')};$('pickDeployment').onclick=()=>modal('Remote Control · Deployment','<p><b>Sample conversation</b></p><p>The latest release passed its checks. Deployment is ready for review.</p><p class="dialog-note">This preview uses sample data. No project conversation was read.</p>')}
function renderRefs(){$('referenceChips').innerHTML=(ref?'<button class="chip" id="removeReference" aria-label="Remove AHU proposal scope reference">@ AHU / Proposal scope &nbsp; ×</button>':'')+attachmentNames.map((n,i)=>`<button class="chip" data-remove-file="${i}">${esc(n)} &nbsp; ×</button>`).join('');if(ref)$('removeReference').onclick=()=>{ref=false;renderRefs()};document.querySelectorAll('[data-remove-file]').forEach(b=>b.onclick=()=>{attachmentNames.splice(Number(b.dataset.removeFile),1);renderRefs()});$('contextRows').innerHTML=ref?'<div class="reference-card"><b>AHU / Proposal scope</b><small>Selected context · Project conversation</small><button id="readSource">Read source ↗</button> &nbsp; · &nbsp; <button id="messageProject">Send message</button></div>':'<p class="muted">No project references added.</p>';if(ref){$('readSource').onclick=readSource;$('messageProject').onclick=sendProject}}
function readSource(){modal('AHU / Proposal scope','<p><b>Sample conversation excerpt</b></p><p>Keep intake, extraction, and verification in scope. Exclude legacy data migration. Plan six weeks for delivery.</p><p class="dialog-note">This source preview uses sample data.</p>')}
function sendProject(){modal('Message project conversation','<p>To <b>AHU / Proposal scope</b></p><textarea class="dialog-input" id="projectMessage" rows="3">Confirm the scope exclusions and six-week delivery schedule.</textarea><p class="dialog-note">Review the message before sending. This demo only simulates delivery.</p><div class="dialog-footer"><button class="small-button" id="cancelSend">Cancel</button><button class="primary" id="approveSend">Approve & send</button></div>');$('cancelSend').onclick=closeModal;$('approveSend').onclick=()=>{const text=$('projectMessage').value.trim();if(!text)return;$('messages').insertAdjacentHTML('beforeend',`<article class="assistant-message"><div class="author"><span class="ai-icon">x0</span> Project message <span class="muted">· Demo</span></div><div class="reply-card"><small>Sent to AHU / Proposal scope · Reply received</small><p>${esc(text)}</p><p><b>Project reply:</b> Confirmed. Legacy data migration is excluded. Delivery is planned over six weeks.</p><button class="activity source-link">Read source ↗</button></div></article>`);document.querySelectorAll('.source-link').forEach(b=>b.onclick=readSource);closeModal();if(innerWidth<981)app.classList.add('files-closed');scrollBottom()}}
['reference','addReference'].forEach(id=>$(id).onclick=references);renderRefs();
function attach(){$('fileInput').click()}['attach','addFiles'].forEach(id=>$(id).onclick=attach);$('fileInput').onchange=()=>{attachmentNames.push(...Array.from($('fileInput').files).map(f=>f.name));renderRefs();toast('Files selected locally. This demo does not upload them.');$('fileInput').value=''};
function scrollBottom(){$('thread').scrollTo({top:$('thread').scrollHeight,behavior:'smooth'})}
function bindMessageActions(){if($('openDocument'))$('openDocument').onclick=()=>setVersion(3);if($('versionsShortcut'))$('versionsShortcut').onclick=versions;if($('handoffDetails'))$('handoffDetails').onclick=details;if($('activity'))$('activity').onclick=()=>$('activityDetail').hidden=!$('activityDetail').hidden;if($('copyReply'))$('copyReply').onclick=async()=>{try{await navigator.clipboard.writeText('The revised proposal is ready. The scope now separates deliverables from exclusions, with a six-week delivery schedule.');toast('Reply copied')}catch{toast('Clipboard unavailable in this browser')}}}
bindMessageActions();
function loadChat(id){active=id;ref=false;attachmentNames=[];renderRefs();$('sidebar').classList.remove('open');document.querySelectorAll('[data-chat]').forEach(b=>b.classList.toggle('selected',b.dataset.chat===id));$('prompt').value='';if(id==='proposal'){lastProvider='Codex';$('provider').value='Codex';$('model').innerHTML='<option>GPT-6 Astra</option><option>Provider default</option>';$('chatTitle').textContent='Proposal for AHU';$('messages').innerHTML=initialMessages;$('chatSubtitle').textContent='Chat · Files stay with this conversation';$('prompt').placeholder='Keep working on the proposal…';$('fileCount').textContent='3';bindMessageActions();if(innerWidth>980)showFiles()}else{$('chatTitle').textContent=id==='new'?'New chat':id==='meeting'?'Prepare for Monday’s meeting':'Research document workflows';$('chatSubtitle').textContent='Chat · No project required';$('fileCount').textContent='0';$('messages').innerHTML=`<div class="empty"><span class="ai-icon" style="font-size:28px;width:auto">x0</span><h2>What are we working on?</h2><p>Bring a document, a question, or an unfinished task.</p><div class="suggestions"><button data-suggestion="Help me revise this proposal.">Work on a document</button><button data-suggestion="Help me research document workflows.">Research a topic</button><button data-suggestion="Summarize the AHU project conversations.">Ask about a project</button></div></div>`;document.querySelectorAll('[data-suggestion]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.suggestion;$('prompt').focus()});$('prompt').placeholder='Ask anything, or attach a file…';app.classList.add('files-closed')} }
$('newChat').onclick=()=>loadChat('new');document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>loadChat(b.dataset.chat));$('search').oninput=()=>document.querySelectorAll('[data-chat]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes($('search').value.toLowerCase()));
$('composer').onsubmit=e=>{e.preventDefault();const text=$('prompt').value.trim();if(!text&&!attachmentNames.length)return;if(document.querySelector('.empty'))$('messages').innerHTML='';if(active==='new')$('chatTitle').textContent=text.slice(0,36)||'Document chat';$('messages').insertAdjacentHTML('beforeend',`<article class="user-message">${attachmentNames.map(n=>`<div class="attachment">▤ ${esc(n)}</div>`).join('')}<p>${esc(text)}</p></article><article class="assistant-message"><div class="author"><span class="ai-icon">x0</span> Remote Control <span class="muted">· Demo response</span></div><p>${active==='proposal'?'In the live workflow, this request would revise the working document and save the next version.':'Your message is shown here. The live workflow would use your selected provider, model, effort, and account.'}</p>${ref?'<button class="activity source-link">Source: AHU / Proposal scope ↗</button>':''}</article>`);document.querySelectorAll('.source-link').forEach(b=>b.onclick=readSource);$('prompt').value='';attachmentNames=[];renderRefs();scrollBottom()};$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('composer').requestSubmit()}if(e.key==='@'&&!$('prompt').value)references()};
let lastProvider='Codex';$('provider').onchange=()=>{const next=$('provider').value;if(active==='new'){applyProvider(next);return}modal('Continue with '+next+'?',`<p>This creates a linked chat with selected context and working files. The original conversation remains available.</p><p class="dialog-note">Provider handoff is proposed for a later release. This draft previews the choice only.</p><div class="dialog-footer"><button class="small-button" id="cancelProvider">Keep ${lastProvider}</button><button class="primary" id="confirmProvider">Preview linked chat</button></div>`);$('provider').value=lastProvider;$('cancelProvider').onclick=closeModal;$('confirmProvider').onclick=()=>{loadChat('new');applyProvider(next);$('chatTitle').textContent='Proposal for AHU · Continued';$('messages').innerHTML='<div class="day">Linked from Proposal for AHU</div><div class="assistant-message"><div class="author"><span class="ai-icon">x0</span>Context handoff · Demo</div><p>Continue the proposal using version 3. Keep scope exclusions and the six-week delivery schedule.</p></div>';$('fileCount').textContent='3';active='proposal';closeModal()}};
function applyProvider(p){lastProvider=p;$('provider').value=p;$('model').innerHTML=p==='Codex'?'<option>GPT-6 Astra</option><option>Provider default</option>':'<option>Provider default</option><option>Sonnet</option><option>Opus</option>';toast(`${p} selected · Model choices are illustrative`)}
$('model').onchange=()=>toast('Model preference updated for this demo');$('effort').onchange=()=>toast('Effort preference updated for this demo');
$('more').onclick=()=>{modal('Conversation actions','<button class="choice" id="rename"><span><b>Rename chat</b></span></button><button class="choice" id="pin"><span><b>Pin chat</b></span></button><button class="choice" id="archive"><span><b>Archive chat</b></span></button><button class="choice" id="continueProject"><span><b>Continue in project</b><small>Later release</small></span></button>');$('rename').onclick=()=>{modal('Rename chat',`<input class="dialog-input" id="newTitle" value="${esc($('chatTitle').textContent)}"><div class="dialog-footer"><button class="primary" id="saveTitle">Save</button></div>`);$('saveTitle').onclick=()=>{const v=$('newTitle').value.trim();if(!v)return;$('chatTitle').textContent=v;const row=document.querySelector(`[data-chat="${active}"] span`);if(row)row.textContent=v;closeModal()}};$('pin').onclick=()=>{closeModal();toast('Chat pinned in this demo')};$('archive').onclick=()=>{closeModal();toast('Archive preview only. Sample chats remain available.')};$('continueProject').onclick=()=>modal('Continue in project','<p>Create a project conversation with selected messages and files from this chat.</p><div class="choice"><span><b>AHU</b><small>Proposed destination</small></span><span class="badge">Later release</span></div>')};
$('controlRoom').onclick=()=>modal('Control room','<p>The existing project workspace stays available alongside Chat.</p><div class="choice"><span><b>AHU</b><small>Project conversations, activity, and files</small></span></div><div class="choice"><span><b>Remote Control</b><small>Development and deployment conversations</small></span></div><p class="dialog-note">Navigation preview only. This draft does not open your live projects.</p>');$('profile').onclick=()=>modal('Personal workspace','<p>Shared preferences and account settings apply across your chats.</p><p class="dialog-note">Sample workspace. No account details are loaded.</p>');$('navToggle').onclick=()=>$('sidebar').classList.toggle('open');document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('sidebar').classList.add('open');$('search').focus()}if(e.key==='Escape')$('sidebar').classList.remove('open')});document.querySelector('.main').addEventListener('click',e=>{if(!e.target.closest('#navToggle'))$('sidebar').classList.remove('open')});if(innerWidth<981)app.classList.add('files-closed');
