const assert = require('node:assert/strict');
const { chromium } = require('/usr/local/lib/node_modules/playwright');
const base = process.argv[2] || 'http://127.0.0.1:8774';
const token = 'browser-fixture-token-0123456789';
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
    await context.addInitScript(t => localStorage.setItem('x056_token', t), token);
    const page = await context.newPage(), errors = [];
    page.on('pageerror', e => errors.push(e.message));
    const api = async (path, data) => {
      const response = await context.request[data ? 'post' : 'get'](base + path, { headers: { Authorization: 'Bearer ' + token }, ...(data ? { data } : {}) });
      assert(response.ok(), await response.text()); return response.json();
    };
    const existing = await api('/api/projects'), cwd = existing.projects.find(p => p.kind !== 'chat').cwd;
    await page.goto(base + '/projects'); await page.locator('#rcSpaceNew').waitFor();
    await page.locator('#rcSpaceNew').click();
    await page.locator('.rc-space-dialog input[name=name]').fill('Project browser proposal');
    await page.locator('.rc-space-dialog button.cr-primary').click();
    await page.locator('[data-overview-new=chat]').first().waitFor();
    const projectId = new URL(page.url()).pathname.split('/')[2];
    await page.locator('.rc-space-tabs a').filter({ hasText: 'Work' }).click();
    await page.getByRole('heading', { name: 'Add a Work project' }).waitFor();
    assert(await page.locator('#rcSpaceNewConversation').isDisabled());
    await page.locator('.rc-space-tabs a').filter({ hasText: 'Files' }).click();
    await page.locator('#rcSpaceUploadInput').setInputFiles({ name: '提案.txt', mimeType: 'text/plain', buffer: Buffer.from('Proposal original') });
    await page.locator('[data-project-file]').waitFor();
    await page.locator('.rc-space-file-menu').click(); await page.getByRole('menuitem', { name: 'Versions', exact: true }).click(); await page.locator('[data-preview]').click();
    await page.getByText('Proposal original', { exact: true }).waitFor(); await page.keyboard.press('Escape');
    await page.locator('.rc-space-tabs a').filter({ hasText: 'Chat' }).click();
    await page.locator('#rcSpaceNewConversation').click();
    await page.locator('.rc-space-dialog input[name=name]').fill('Proposal conversation');
    await page.locator('.rc-space-dialog select[name=provider]').selectOption('claude');
    await page.locator('.rc-space-dialog button.cr-primary').click();
    await page.locator('#rcChatFiles').waitFor();
    const chatId = new URL(page.url()).pathname.split('/')[2];
    await page.locator('#prompt').fill('Unsent proposal draft');
    await page.locator('#crBreadcrumb a[href^="/projects/"]').click();await page.locator('.rc-space-tabs a').filter({ hasText: 'Files' }).click();
    await page.locator('.rc-space-file-menu').click(); await page.getByRole('menuitem', { name: 'Use in conversation', exact: true }).click();
    await page.locator('.rc-space-dialog [data-execution]').filter({ hasText: 'Proposal conversation' }).click();
    await page.waitForFunction(() => document.querySelector('#prompt').value === 'Unsent proposal draft');
    assert.equal(new URL(page.url()).pathname, '/chat/' + chatId);
    await page.reload(); await page.locator('#rcChatFiles').waitFor();
    assert.equal(await page.locator('#prompt').inputValue(), 'Unsent proposal draft');
    const chatState = await api('/api/chats/' + chatId);
    const attachments = await page.evaluate(id => JSON.parse(localStorage.getItem('x056_chat_attachments_' + id + '::' + window.rcTestSession) || '[]'), chatId).catch(() => []);
    const saved = await page.evaluate(({ id, sid }) => JSON.parse(localStorage.getItem('x056_chat_attachments_' + id + '::' + sid) || '[]'), { id: chatId, sid: chatState.lastSessionId });
    assert.equal(saved[0].ownerId, projectId);
    await api('/api/memory/entry', { entry: { spaceId:projectId,scope:'space', title: 'Project brief', kind: 'context', tags: ['project-brief'], content: 'Retain editable proposal originals.', status: 'confirmed', pinned: true } });
    await page.locator('#moreBtn').click();await page.getByRole('menuitem',{name:'Conversation memory'}).click();
    await page.getByText('Project brief', { exact: true }).first().waitFor(); await page.keyboard.press('Escape');
    await page.locator('#crBreadcrumb a[href^="/projects/"]').click();
    await page.locator('.rc-space-tabs a').filter({ hasText: 'Work' }).click();
    await page.locator('#rcSpaceAddWork').click();
    await page.locator('.rc-space-dialog input[name=name]').fill('Proposal Work repository');
    await page.locator('.rc-space-dialog input[name=cwd]').fill(cwd);
    await page.locator('.rc-space-dialog button.cr-primary').click();await page.locator('[data-preview]').click();await page.locator('.rc-space-dialog button.cr-primary').click();await page.locator('.rc-space-dialog').waitFor({state:'detached'});
    await page.locator('#rcSpaceNewConversation').click();
    await page.locator('.rc-space-dialog input[name=name]').fill('Work on proposal');
    const option=await page.locator('select[name=workProjectId] option').filter({hasText:'Proposal Work repository'}).getAttribute('value');await page.locator('select[name=workProjectId]').selectOption(option);
    await page.locator('.rc-space-dialog select[name=provider]').selectOption('claude');
    await page.locator('.rc-space-dialog button.cr-primary').click();
    await page.waitForURL(/\/work\/[^/]+\/[^/]+$/); await page.locator('#prompt').waitFor();
    const workPath = new URL(page.url()).pathname;
    await page.locator('#prompt').fill('Unsent Work draft');
    await page.locator('#crBreadcrumb a[href^="/projects/"]').click();
    await page.locator('.rc-space-tabs a').filter({ hasText: 'Memory' }).click();
    await page.locator('#rcProjectBody #crMemory').waitFor();
    await page.getByText('Project brief', { exact: true }).first().waitFor();
    await page.goto(base + workPath); await page.locator('#prompt').waitFor();
    assert.equal(await page.locator('#prompt').inputValue(), 'Unsent Work draft');
    await page.reload(); await page.locator('#prompt').waitFor();
    assert.equal(new URL(page.url()).pathname, workPath);
    await page.locator('#crBreadcrumb a[href^="/projects/"]').click();
    await page.screenshot({ path: '/tmp/project-spaces-desktop.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.locator('#rcProjectPage').evaluate(e => e.scrollWidth <= e.clientWidth + 1));
    await page.screenshot({ path: '/tmp/project-spaces-mobile.png' });
    await page.locator('#crProjects').click(); await page.locator('#crSpacesTab').click();
    await page.locator('#rcSpaceNew').waitFor();
    const signedOut = await browser.newContext(); const login = await signedOut.newPage();
    login.on('pageerror', e => errors.push(e.message));
    await login.goto(base + workPath); await login.locator('#gateToken').fill(token); await login.locator('#gateTokenBtn').click();
    await login.locator('#prompt').waitFor(); assert.equal(new URL(login.url()).pathname, workPath); await signedOut.close();
    assert.deepEqual(errors, []); console.log('Project routes, files, memory, drafts, workspace setup, mobile and direct sign-in passed.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
